// Shared TypeScript types for 더본투비
// Domain types will be generated by Prisma client in US-002

export type NavItem = {
  label: string;
  href: string;
  icon?: string;
  badge?: number;
  children?: NavItem[];
};

export type KPIStat = {
  label: string;
  value: string;
  change: number;
  changeLabel: string;
};
